volumes:
  data:
  data-bkp:
services:
  springbootapp:
    image: lerndevops/springboot-mongo-app:latest
    ports:
      - 8080
    depends_on:
      - mongo
  mongo:
    image: lerndevops/mongo
    ports:  
      - 27017:27017
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
